### PR TITLE
Laravel 6 support

### PR DESCRIPTION
**Pull request by Flerex**

### CODE REVIEW

**Comment by xdvx** [comment]
Thanks, merged.

**Comment by Flerex** [comment]
@xdvx you need to create a new tag with the new version for the installation command in the README.md to work.

**Comment by gtjamesa** [comment]
@xdvx Can you tag this release please?

**Comment by xdvx** [comment]
Sorry guys missed your messages and forgot to update the new version tag. It should work now.

**Comment by gtjamesa** [comment]
Thanks for getting back so quickly. Sorry to be a pain, but could you publish 0.1.3 to packagist?

**Comment by xdvx** [comment]
I see it is already at 0.1.3, isn't it?

**Comment by gtjamesa** [comment]
Ah, it must have been cached yesterday when I checked as it was still displaying 0.1.2 on packagist. Thanks again for the quick response, and for the great package!

**Pull request merged**
